import type {Metadata} from 'next'
import {Lato} from 'next/font/google'
import './globals.css'
import Nav from '@/components/Nav'
const lato = Lato({subsets: ['latin'], weight: ['400']})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang='en'>
      <body className={lato.className}>
        <Nav />
        {children}
      </body>
    </html>
  )
}
